f=open(r'd:\Toilet\toilet_partition_auto_generator.html','r',encoding='utf-8')
s=f.read()
f.close()
s=s.replace('bold 30px','bold 22px')
s=s.replace('30px','22px')
f=open(r'd:\Toilet\toilet_partition_auto_generator.html','w',encoding='utf-8')
f.write(s)
f.close()
print('done')