const fs = require('fs');
const path = require('path');

const htmlPath = path.join(__dirname, '..', 'toilet_partition_auto_generator_V2Pro.html');
const source = fs.readFileSync(htmlPath, 'utf8');

function sectionBetween(startNeedle, endNeedle) {
  const start = source.indexOf(startNeedle);
  if (start < 0) throw new Error(`Missing ${startNeedle}`);
  const end = source.indexOf(endNeedle, start + startNeedle.length);
  if (end < 0) throw new Error(`Missing ${endNeedle}`);
  return source.slice(start, end);
}

function assertIncludes(haystack, needle, message) {
  if (!haystack.includes(needle)) throw new Error(message);
}

function assertNotIncludes(haystack, needle, message) {
  if (haystack.includes(needle)) throw new Error(message);
}

const drawElevationDim = sectionBetween('function drawElevationDim', 'function drawLeftOuterDepthDim');
const frontLayout = sectionBetween('function frontElevationLayout', 'function frontDoorSwingSegments');
const frontHelpers = sectionBetween('function frontTouchesMiddlePostEdge', 'function drawFront(p)');
const frontHeaderCanvas = sectionBetween('function drawFrontHeaderPanelsCanvas', 'function drawFrontDoorAnnotationsCanvas');
const drawFront = sectionBetween('function drawFront(p)', 'function drawDetailCallout');
const frontDoorLoop = sectionBetween("ctx.strokeRect(door.x, door.y, door.w, door.h);", 'const topDimY = L.oy - frontDimOffsetPx()');
const backendFront = sectionBetween('function buildFrontPageDrawingModel', 'function buildSidePageDrawingModel');
const inputBindings = sectionBetween('function commitHeightFieldOnEnter', "document.getElementById('canvas-text-editor')");

assertIncludes(frontLayout, 'const hVisMm = Number(p.hVis) || 1830', 'front layout should keep a real visible-board height in mm.');
assertIncludes(frontLayout, 'const H = Math.max(hUMm, hMidMm, hDoorMm, hVisMm)', 'front overall height should include visible-board height.');
assertIncludes(frontLayout, 'post.y = floor - hMid', 'front middle partitions should use real middle-partition height.');
assertIncludes(frontLayout, 'post.h = hMid', 'front middle partitions should use real middle-partition height for drawing.');
assertIncludes(frontLayout, 'booths.push({index:i, x:boothX, y:floor - vis', 'front visible/fixed panels should start from their own visible-board height, not middle-partition height.');
assertIncludes(drawElevationDim, 'planFont', 'drawElevationDim should use planFont so elevation dimension text follows plan text scaling.');
assertIncludes(drawElevationDim, 'anno(', 'drawElevationDim should use anno() so dimension offsets/ticks follow plan annotation scaling.');
assertIncludes(drawElevationDim, 'Number.isFinite(Number(side)) ? Number(side) : 36', 'drawElevationDim should preserve side=0 so centered door-panel dimensions stay centered.');
assertIncludes(drawElevationDim, 'const verticalTextGap = unit(Number(options.verticalTextGap ?? 0) || 12)', 'drawElevationDim should use a small CAD-style gap between vertical dimension line and text.');
assertIncludes(drawElevationDim, 'Number(side) === 0 ? dx + verticalTextGap : dx + (side < 0 ? -unit(44) : unit(44))', 'drawElevationDim should keep side=0 vertical text beside, not on top of, the dimension line.');
assertNotIncludes(drawElevationDim, 'Number(side || 36)', 'drawElevationDim must not treat side=0 as the default offset.');
assertIncludes(frontHelpers, 'Math.max(0.25, anno(', 'front helper line widths should use fine plan-style scaled line widths.');
assertIncludes(drawFront, 'const prevAnnoScale = planAnnotationScale', 'drawFront should set planAnnotationScale from front scale and restore it.');
assertIncludes(drawFront, 'planAnnotationScale = 0.115', 'drawFront should use a restrained CAD-style annotation scale, not the raw front geometry scale.');
assertIncludes(drawFront, 'Math.max(0.25, anno(2.2))', 'front primary lines should be fine CAD-style strokes.');
assertIncludes(drawFront, 'post.index > 0 && post.index < L.count', 'front middle upright panels should be styled separately from edge uprights.');
assertNotIncludes(source, 'front-middle-upright-panel', 'front elevation should not draw a separate middle partition expression.');
assertIncludes(drawFront, "ctx.strokeStyle = '#000000'", 'front middle partition and non-door board strokes should be black.');
assertNotIncludes(drawFront, 'ctx.setLineDash([anno(12), anno(10)])', 'front middle partition thickness should not be drawn dashed.');
assertNotIncludes(backendFront, 'dash:[4,4], className:\'front-middle-upright-panel\'', 'backend middle partition thickness should not be drawn dashed.');
assertIncludes(drawFront, 'if (isMiddlePost) return', 'canvas front elevation should skip drawing middle partition expressions.');
assertIncludes(backendFront, 'if (isMiddlePost) return', 'backend front elevation should skip drawing middle partition expressions.');
assertNotIncludes(source, "B.line(model, post.x, post.y, post.x, post.y + post.h, {stroke:'#000', strokeWidth:0.35, className:'front-middle-upright-panel'});", 'backend middle partition should not draw a separate internal left expression line.');
assertNotIncludes(source, "B.line(model, post.x + post.w, post.y, post.x + post.w, post.y + post.h, {stroke:'#000', strokeWidth:0.35, className:'front-middle-upright-panel'});", 'backend middle partition should not draw a separate internal right expression line.');
assertIncludes(frontHelpers, 'ctx.setLineDash([])', 'front fixed panel helper should not leave dashed state active.');
assertIncludes(source, 'frontMiddlePostRanges', 'front panel segment lines should avoid middle partition thickness ranges.');
assertIncludes(source, 'frontTouchesMiddlePostEdge', 'front fixed panel seams should omit vertical edges that duplicate middle partition thickness lines.');
assertNotIncludes(drawFront, 'ctx.moveTo(post.x, post.y)', 'front middle partition should not draw separate internal thickness lines.');
assertNotIncludes(source, 'drawFrontVisiblePanelsCanvas', 'front elevation should not keep a full-booth visible-panel background frame helper.');
assertNotIncludes(source, 'backendDrawFrontVisiblePanels', 'backend front elevation should not keep a full-booth visible-panel background frame helper.');
assertNotIncludes(drawFront, 'ctx.strokeRect(booth.x, booth.y, booth.w, booth.h)', 'front visible panels must not use full strokeRect because it creates a center line inside middle partitions.');
assertNotIncludes(backendFront, "B.rect(model, booth.x, booth.y, booth.w, booth.h, {fill:'none', stroke:'#6a9bcc'", 'backend front visible panels must not use full rect because it creates a center line inside middle partitions.');
assertNotIncludes(frontHelpers, "ctx.strokeStyle = '#8fb2d6'", 'front fixed/front panel seams should be black, not blue.');
assertNotIncludes(backendFront, "stroke:'#8fb2d6'", 'backend front fixed/front panel seams should be black, not blue.');
assertNotIncludes(drawFront, "#378ADD", 'front middle partition board lines should be black, not blue.');
assertNotIncludes(backendFront, "#378ADD", 'backend front middle partition board lines should be black, not blue.');
assertIncludes(drawFront, "ctx.strokeStyle = '#185FA5'", 'front door panels should keep the current blue.');
assertIncludes(source, 'hHeader:0, hHeaderGap:0', 'door header height and header-door gap should default to 0.');
assertIncludes(source, "className:'front-door-header-panel'", 'front header panels should have a distinct class.');
assertIncludes(frontHeaderCanvas, "ctx.strokeStyle = '#185FA5'", 'canvas front header panels should use the same blue stroke as door panels.');
assertIncludes(source, "stroke:'#185FA5', strokeWidth:1, className:'front-door-header-panel'", 'front header panels should use the same blue stroke as door panels.');
assertIncludes(frontDoorLoop, "ctx.strokeStyle = '#185FA5'", 'front door swing direction should keep the current blue color.');
assertIncludes(frontDoorLoop, 'ctx.setLineDash([anno(84), anno(18)])', 'front door swing direction should use long segments with short breaks like the reference.');
assertIncludes(backendFront, "className:'front-door-swing-segment'", 'backend front door swing direction should be present.');
assertIncludes(backendFront, "{stroke:'#185FA5', strokeWidth:0.6, dash:[30,7], className:'front-door-swing-segment'}", 'backend front door swing direction should keep blue color with long segments and short breaks like the reference.');
assertNotIncludes(drawFront, 'ctx.strokeRect(L.ox, L.oy, L.sW, L.sH)', 'front elevation should not draw a black overall body frame over real component lines.');
assertNotIncludes(backendFront, "className:'front-outline'", 'backend front elevation should not draw a black overall body frame over real component lines.');
assertNotIncludes(frontHelpers, 'ctx.moveTo(L.ox, L.floor - L.hU)', 'front elevation should not draw a continuous top finish line across separate boards.');
assertNotIncludes(frontHelpers, "className:'front-top-finish-line'", 'backend front elevation should not draw a continuous top finish line across separate boards.');
assertNotIncludes(drawFront, 'ctx.strokeRect(x, L.floor - L.vis, w, L.vis)', 'front rebate panels should not draw an extra full rectangle over visible/front panel lines.');
assertNotIncludes(backendFront, "className:'front-rebate-panel'", 'backend front rebate panels should not draw an extra full rectangle over visible/front panel lines.');
assertIncludes(drawFront, 'frontDoorSwingSegments(door', 'front elevation should keep door opening direction indicators.');
assertIncludes(backendFront, 'frontDoorSwingSegments(door', 'backend front elevation should keep door opening direction indicators.');
assertIncludes(drawFront, 'drawElevationDim(', 'front elevation should keep outside dimension annotations.');
assertIncludes(backendFront, 'backendDrawDim(', 'backend front elevation should keep outside dimension annotations.');
assertNotIncludes(drawFront, 'drawFrontDatumCanvas(L)', 'canvas front elevation should not draw the F.F.L. datum line or label.');
assertNotIncludes(backendFront, 'backendDrawFrontDatum(B, model, L)', 'backend front elevation should not draw the F.F.L. datum line or label.');
assertNotIncludes(backendFront, 'front-ffl-line', 'backend front elevation should not output a front F.F.L. dashed line class.');
assertNotIncludes(backendFront, 'front-ffl-label', 'backend front elevation should not output a front F.F.L. label class.');
assertIncludes(source, 'function frontDimValue(value)', 'front elevation should have a helper for dimension values without text/mm suffixes.');
assertIncludes(source, 'verticalTextGap: frontDimTextGapPx()', 'front elevation height dimensions should use the unified print-mm text gap.');
assertIncludes(source, 'dimOffsetMm: 10', 'front elevation dimensions should use one print-mm offset from the main body.');
assertIncludes(source, 'textGapMm: 2', 'front elevation dimension text should use one print-mm text gap.');
assertNotIncludes(source, 'totalGap: 46', 'front elevation should not use ad hoc pixel top dimension offsets.');
assertNotIncludes(source, 'bottomDimGap: 56', 'front elevation should not use ad hoc pixel bottom dimension offsets.');
assertIncludes(source, 'function frontPrintMmPx(mm)', 'front elevation should convert print millimeters to drawing pixels for dimension spacing.');
assertIncludes(source, 'function frontDimOffsetPx() {', 'front elevation should centralize dimension offset conversion.');
assertIncludes(source, 'function frontDimTextGapPx() {', 'front elevation should centralize dimension text-gap conversion.');
assertNotIncludes(drawFront, 'if (L.count <= 1) L.doors.forEach', 'front elevation should show door panel width dimensions for every door, not only single-door layouts.');
assertIncludes(source, 'function frontBottomDimSegments(L)', 'front elevation should build one bottom dimension chain like the plan view.');
assertIncludes(source, '...(L.boardModel?.panels || []).map(panel => ({', 'front bottom dimension chain should include all front edge panels.');
assertIncludes(source, '...(L.boardModel?.doors || []).map(door => ({', 'front bottom dimension chain should include all door panels.');
assertIncludes(drawFront, 'const topDimY = L.oy - frontDimOffsetPx()', 'canvas front top dimension should use the unified body offset.');
assertIncludes(drawFront, 'const bottomDimY = L.floor + frontDimOffsetPx()', 'canvas front bottom dimension should use the unified body offset.');
assertIncludes(drawFront, 'drawChainDim(bottomDimY, frontBottomDimSegments(L), FRONT_DIM.strokeStyle)', 'canvas front elevation should draw a single plan-style bottom dimension chain.');
assertNotIncludes(drawFront, 'drawElevationDim(door.x, doorWidthDimY, door.x + door.w, doorWidthDimY', 'canvas front door widths should not use elevation dimensions that overlap the body.');
assertIncludes(source, 'label:frontDimValue(panel.bigMm)', 'front panel dimensions should use each actual front edge panel size.');
assertIncludes(source, 'label:frontDimValue(door.bigMm)', 'door panel dimensions should use each actual door panel size.');
assertNotIncludes(drawFront, 'drawFrontBoothChainCanvas(L)', 'front elevation should not draw a separate booth-width chain below the plan-style bottom chain.');
assertNotIncludes(drawFront, 'drawChainDim(frontPanelDimY', 'front elevation should not draw a separate front panel chain.');
assertNotIncludes(drawFront, 'drawChainDim(doorWidthDimY', 'front elevation should not draw a separate door width chain.');
assertIncludes(backendFront, 'const topDimY = L.oy - frontDimOffsetPx()', 'backend front top dimension should use the unified body offset.');
assertIncludes(backendFront, 'const bottomDimY = L.floor + frontDimOffsetPx()', 'backend front bottom dimension should use the unified body offset.');
assertIncludes(backendFront, "backendDrawChainDim(B, model, bottomDimY, frontBottomDimSegments(L), FRONT_DIM.chainFontSize, 'front-bottom-dimension')", 'backend front elevation should draw one plan-style bottom dimension chain.');
assertNotIncludes(backendFront, "backendDrawDim(B, model, door.x, doorWidthDimY, door.x + door.w, doorWidthDimY", 'backend front door widths should not use elevation dimensions that overlap the body.');
assertIncludes(drawFront, 'const firstDoor = L.doors[0]', 'canvas front door height dimension should use the first door only.');
assertIncludes(drawFront, 'const uprightDimX = L.ox - (L.walls.left ? L.swt : 0) - frontDimOffsetPx()', 'canvas front upright height dimension should sit outside the main body with the unified offset.');
assertIncludes(drawFront, 'drawElevationDim(uprightDimX, L.floor - L.hU, uprightDimX, L.floor, frontDimValue(p.hUpright), -1', 'canvas front upright height dimension should be outside the body, not centered on the upright.');
assertNotIncludes(drawFront, 'drawElevationDim(leftHeightDimX, L.floor - L.hU, leftHeightDimX, L.floor, frontDimValue(p.hUpright), -1', 'canvas front upright height dimension should not use the old outside offset style.');
assertIncludes(drawFront, 'if (firstDoor) drawElevationDim(firstDoor.x + firstDoor.w / 2, firstDoor.y, firstDoor.x + firstDoor.w / 2, firstDoor.y + firstDoor.h, frontDimValue(p.hDoor || 1750)', 'canvas front door height dimension should be centered on the first door panel and plain numeric.');
assertIncludes(backendFront, 'const firstDoor = L.doors[0]', 'backend front door height dimension should use the first door only.');
assertIncludes(backendFront, 'const uprightDimX = L.ox - (L.walls.left ? L.swt : 0) - frontDimOffsetPx()', 'backend front upright height dimension should sit outside the main body with the unified offset.');
assertIncludes(backendFront, 'backendDrawDim(B, model, uprightDimX, L.floor - L.hU, uprightDimX, L.floor, frontDimValue(p.hUpright), -1', 'backend front upright height dimension should be outside the body, not centered on the upright.');
assertNotIncludes(backendFront, 'backendDrawDim(B, model, leftHeightDimX, L.floor - L.hU, leftHeightDimX, L.floor, frontDimValue(p.hUpright), -1', 'backend front upright height dimension should not use the old outside offset style.');
assertIncludes(backendFront, 'if (firstDoor) backendDrawDim(B, model, firstDoor.x + firstDoor.w / 2, firstDoor.y, firstDoor.x + firstDoor.w / 2, firstDoor.y + firstDoor.h, frontDimValue(p.hDoor || 1750)', 'backend front door height dimension should be centered on the first door panel and plain numeric.');
assertNotIncludes(drawFront, 'L.doors.forEach(door => drawElevationDim(door.x + door.w / 2, door.y', 'canvas front door height dimension should not repeat on every door.');
assertNotIncludes(backendFront, 'L.doors.forEach(door => backendDrawDim(B, model, door.x + door.w / 2, door.y', 'backend front door height dimension should not repeat on every door.');
assertIncludes(drawFront, 'L.headerPanels.forEach(panel => drawElevationDim(panel.x + panel.w / 2, panel.y, panel.x + panel.w / 2, panel.y + panel.h, frontDimValue(panel.heightMm)', 'canvas front header panel height dimensions should be centered on each header panel and plain numeric.');
assertIncludes(backendFront, 'L.headerPanels.forEach(panel => backendDrawDim(B, model, panel.x + panel.w / 2, panel.y, panel.x + panel.w / 2, panel.y + panel.h, frontDimValue(panel.heightMm)', 'backend front header panel height dimensions should be centered on each header panel and plain numeric.');
assertNotIncludes(drawFront, '`立板高 ${p.hUpright}mm`', 'canvas front upright height dimension should not include text or mm suffix.');
assertNotIncludes(drawFront, '`门高 ${p.hDoor || 1750}mm`', 'canvas front door height dimension should not include text or mm suffix.');
assertNotIncludes(backendFront, '`立板高 ${p.hUpright}mm`', 'backend front upright height dimension should not include text or mm suffix.');
assertNotIncludes(backendFront, '`门高 ${p.hDoor || 1750}mm`', 'backend front door height dimension should not include text or mm suffix.');
assertNotIncludes(drawFront, 'drawFrontDoorAnnotationsCanvas(L)', 'front elevation should not draw door tag or swing text inside the body.');
assertNotIncludes(backendFront, 'backendDrawFrontDoorAnnotations(B, model, L)', 'backend front elevation should not draw door tag or swing text inside the body.');
assertNotIncludes(drawFront, "fillText('鏃犻棬'", 'front elevation should not draw no-door text.');
assertNotIncludes(backendFront, "className:'front-no-door-outline'", 'backend front elevation should not draw no-door outline frames.');
assertNotIncludes(drawFront, 'ctx.strokeRect(booth.x + 4, L.floor - L.hDoor', 'front elevation should not draw no-door outline frames.');
assertNotIncludes(backendFront, "className:'front-no-door-label'", 'backend front elevation should not draw no-door text.');
assertNotIncludes(frontHelpers, 'ctx.fillText(booth.label', 'front visible panels should not draw booth labels.');
assertNotIncludes(frontHelpers, 'B.text(model, booth.label', 'backend front visible panels should not draw booth labels.');
assertNotIncludes(drawFront, 'P${index + 1}', 'front elevation should not draw P labels.');
assertNotIncludes(backendFront, 'P${index + 1}', 'backend front elevation should not draw P labels.');
assertIncludes(inputBindings, 'function commitHeightFieldOnEnter', 'height inputs should commit through an Enter-only helper.');
assertIncludes(inputBindings, "if (['h-upright','h-door','h-mid','h-vis'].includes(el.id)) return", 'height inputs should not commit on blur/change through the generic field handler.');
assertIncludes(inputBindings, 'commitHeightFieldOnEnter(el.id)', 'height inputs should commit when Enter is pressed.');
assertNotIncludes(inputBindings, "heightInput?.addEventListener('input'", 'height inputs should not redraw on every input event.');
assertNotIncludes(inputBindings, "document.getElementById('h-upright').addEventListener('change'", 'upright height should not commit on blur/change.');

console.log('front style contract ok');
